### ISSUE TITLE
Versiyon kontrolu

### ISSUE THREAD

**Issue by onurozgurozkan** [Projekod/Bulutfon-Opencart-Eklentisi#1]
Benim şahsi görüşüm eklentinin versiyonu bir yerde yazmalı. Hata yeni versiyonu çıkınca kırmızı olup yeni bir versiyon var diye link verebilir.

Misal github üzerinden version.json parse edilip. Yeni sürüm kontrol edilebilir. Hatta changelog.md veya update.md gibi bir dosyaya link verilebilir.

Biz her ne kadar toplu duruyu yapsak bile eski kullanıcılar yeni versiyonlardan haberdar olmayabilir.

**Comment by aligundogdu** [comment]
Mantıklı  ekliyorum iş listesine.

**Comment by onurozgurozkan** [comment]
@aligundogdu @ahmetilhann her şey bir tarafa bir VERSION.txt atılsa ve semver'e göre güncelleme yapılsa bile başlangıçta yeterli olacaktır. Şimdi kullanıcı tarafında hangi versiyonlar var bilmiyoruz.

**Comment by ahmetilhann** [comment]
Versiyon bilgileri dosyayarini ekledim
